import { useState, useEffect, useCallback } from "react";
import { getDigestForCity, SupportedCity } from "../data/live-digest";

/**
 * Returns the script for a specific post, localized to the user's city.
 *
 * For city tab: looks up script from city digest.
 * For state/nation: looks up from that scope's data.
 * Localized scripts (generated by localize-scripts.js) will replace
 * the generic ones in the data once generated per city.
 */
export function useAdaptations(
  contentUrl: string,
  marketCity: string,
  contentStyle?: string,
  scope?: "state" | "nation",
) {
  const [script, setScript] = useState("");
  const [loading, setLoading] = useState(true);

  const fetchScript = useCallback(async () => {
    setLoading(true);
    try {
      await new Promise((r) => setTimeout(r, 200));

      let found = false;

      if (scope) {
        // State or nation tab — use localized script for user's city
        const scopeKey = scope === "state" ? "Florida" : "USA";
        const scopeItems = getDigestForCity(scopeKey as SupportedCity);
        const item = scopeItems.find((d) => d.url === contentUrl);
        if (item) {
          // Prefer localized script for user's city, fall back to generic
          const localized = item.localizedScripts?.[marketCity];
          setScript(localized || item.script);
          found = true;
        }
      }

      if (!found) {
        // City tab or fallback — search user's city data
        const cityItems = getDigestForCity(marketCity as SupportedCity);
        const item = cityItems.find((d) => d.url === contentUrl);
        if (item) {
          setScript(item.script);
          found = true;
        }
      }

      if (!found) {
        setScript("Script not found for this reel.");
      }
    } catch {
      setScript("");
    } finally {
      setLoading(false);
    }
  }, [contentUrl, marketCity, contentStyle, scope]);

  useEffect(() => {
    fetchScript();
  }, [fetchScript]);

  const adaptations = script
    ? [{ versionNumber: 1, hook: "", fullScript: script, suggestedPostTime: "", cta: "" }]
    : [];

  return { adaptations, script, loading, refresh: fetchScript };
}
